/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type StorageSet = ContractEventLog<{
  _message: string;
  0: string;
}>;

export interface SimpleStorage extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): SimpleStorage;
  clone(): SimpleStorage;
  methods: {
    storedData(): NonPayableTransactionObject<string>;

    setStore(x: number | string): NonPayableTransactionObject<void>;

    get(): NonPayableTransactionObject<string>;
  };
  events: {
    StorageSet(cb?: Callback<StorageSet>): EventEmitter;
    StorageSet(options?: EventOptions, cb?: Callback<StorageSet>): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "StorageSet", cb: Callback<StorageSet>): void;
  once(
    event: "StorageSet",
    options: EventOptions,
    cb: Callback<StorageSet>
  ): void;
}
